In [26]:
# importação de bibliotecas

import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

#Analise exploratoria de dados

In [2]:
imob = pd.read_csv('dataset_2.csv')

In [3]:
imob.head()

,Area_SqFt,Rooms,Build_Year,Location,Street_Type,Furnishing,Property_Type,Has_Pool,Price
0,2473.192784,4.0,1992,Jaipur,Residential Lane,Furnished,Apartment,No,568486.0
1,2353.472711,4.0,2006,Indore,Corner Plot,Unfurnished,Apartment,Yes,577214.0
2,2212.222005,3.0,2012,Jaipur,Highway Facing,Semi-Furnished,Duplex,No,581300.0
3,2823.886596,6.0,1993,Lucknow,Main Road,Unfurnished,Villa,Yes,794614.0
4,1869.648721,5.0,2012,Jaipur,Corner Plot,Semi-Furnished,Apartment,No,493086.0

In [4]:
imob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1124 entries, 0 to 1123
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Area_SqFt      1091 non-null   float64
 1   Rooms          1091 non-null   float64
 2   Build_Year     1124 non-null   int64
 3   Location       1124 non-null   object
 4   Street_Type    1124 non-null   object
 5   Furnishing     1091 non-null   object
 6   Property_Type  1124 non-null   object
 7   Has_Pool       1124 non-null   object
 8   Price          1124 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 79.2+ KB

In [5]:
imob.isna().sum()

Area_SqFt        33
Rooms            33
Build_Year        0
Location          0
Street_Type       0
Furnishing       33
Property_Type     0
Has_Pool          0
Price             0
dtype: int64

In [6]:
linhas_vazias_sqrt = imob[imob['Area_SqFt'].isna()].index

In [8]:
linhas_vazias_rooms = imob[imob['Rooms'].isna()].index

In [13]:
linhas_vazias_furnishing = imob[imob['Furnishing'].isna()].index

In [14]:
linhas_vazias_sqrt
linhas_vazias_furnishing
linhas_vazias_rooms

Index([  56,   87,  118,  125,  127,  157,  171,  182,  186,  274,  308,  348,
        382,  394,  417,  451,  454,  482,  648,  651,  783,  798,  898,  912,
        947,  976,  977,  990, 1017, 1025, 1044, 1057, 1093],
      dtype='int64')

In [15]:
linhas_vazias_rooms

Index([  56,   87,  118,  125,  127,  157,  171,  182,  186,  274,  308,  348,
        382,  394,  417,  451,  454,  482,  648,  651,  783,  798,  898,  912,
        947,  976,  977,  990, 1017, 1025, 1044, 1057, 1093],
      dtype='int64')

In [16]:


# Comparando se são exatamente as mesmas linhas
sao_iguais = linhas_vazias_sqrt.equals(linhas_vazias_rooms)
print("As linhas vazias são as mesmas?", sao_iguais)

As linhas vazias são as mesmas? False

In [17]:
imob.dropna(subset=['Area_SqFt', 'Rooms', 'Furnishing'], inplace=True)

In [18]:
imob.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1027 entries, 0 to 1123
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Area_SqFt      1027 non-null   float64
 1   Rooms          1027 non-null   float64
 2   Build_Year     1027 non-null   int64
 3   Location       1027 non-null   object
 4   Street_Type    1027 non-null   object
 5   Furnishing     1027 non-null   object
 6   Property_Type  1027 non-null   object
 7   Has_Pool       1027 non-null   object
 8   Price          1027 non-null   float64
dtypes: float64(3), int64(1), object(5)
memory usage: 80.2+ KB

In [20]:
imob.isna().sum()

Area_SqFt        0
Rooms            0
Build_Year       0
Location         0
Street_Type      0
Furnishing       0
Property_Type    0
Has_Pool         0
Price            0
dtype: int64

In [21]:
imob.describe()

          Area_SqFt        Rooms   Build_Year         Price
count   1027.000000  1027.000000  1027.000000  1.027000e+03
mean    2238.749462     4.566699  2005.081792  6.098391e+05
std      744.704478     1.676631    11.791113  1.450773e+05
min      700.000000     2.000000  1985.000000  2.486400e+05
25%     1826.724874     3.000000  1995.000000  5.177645e+05
50%     2206.565229     5.000000  2005.000000  6.032640e+05
75%     2578.977535     6.000000  2015.000000  6.897460e+05
max    10267.124330     7.000000  2024.000000  2.071402e+06

In [24]:
#visualizando dados

plt.figure(figsize=(14,6))
plt.subplot(4,1,1)
sns.histplot('Area_SqFt', bins=30)

TypeError: 'module' object is not callable